version: "3.8"
services:
  # frontend-service:
  #   container_name: todo-frontend
  #   restart: always
  #   build:
  #     context: ../
  #     dockerfile: ./docker/frontend-dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - backend-service
  #     - database-service

  backend-service:
    container_name: todo-backend
    restart: always
    build:
      context: ../
      dockerfile: ./docker/backend-dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: container
      Authentication__ApiKey: ${AUTHENTICATION_APIKEY}
      DatabaseSettings__ConnectionString: ${DATABASESETTINGS_CONNECTIONSTRING}

    depends_on:
      - database-service

  database-service:
    image: postgres
    container_name: todo-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - todo-data:/data/tododb

volumes:
  todo-data:
