version: "3.8"
services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - todo-data:/data/tododb

  backend:
    container_name: backend
    restart: always
    build:
      context: ../
      dockerfile: docker/backend-dockerfile
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Container
      ASPNETCORE_URLS: "http://+:5000"
      Auth__ApiKey: ${API_KEY}
      DatabaseSettings__ConnectionString: "Host=db;Port=5432;Database=todo;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};"
    depends_on:
      - db

  frontend:
    container_name: frontend
    restart: always
    build:
      context: ../
      dockerfile: ./docker/frontend-dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Container
      ASPNETCORE_URLS: "http://+:4000"
      TodoApi__Url: "http://backend:5000/api/v1/todos"
      TodoApi__ApiKey: ${API_KEY}
    ports:
      - "4000:4000"
    depends_on:
      - backend

volumes:
  todo-data:
