version: "3.8"
services:
  frontend-service:
    container_name: todo-frontend
    restart: always
    build:
      context: ../
      dockerfile: ./docker/frontend-dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Container
      BackendService__Host: "todo-backend/api/v1/todos"
      BackendService__ApiKey: df5cb460a71dc6d56ad068cafa6c9280
    ports:
      - "4000:8080"
    depends_on:
      - backend-service
      - database-service

  backend-service:
    container_name: todo-backend
    restart: always
    build:
      context: ../
      dockerfile: docker/backend-dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Container
      Authentication__ApiKey: "df5cb460a71dc6d56ad068cafa6c9280"
      DatabaseSettings__ConnectionString: "Host=todo-database;Port=5432;Database=todo;Username=dev;Password=devpsw;"
    depends_on:
      - database-service

  database-service:
    image: postgres
    container_name: todo-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpsw
    volumes:
      - todo-data:/data/tododb

volumes:
  todo-data:
